services:

  sheets_backend:
    container_name: sheets_backend
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    build:
      context: app
      dockerfile: ../Dockerfile
    volumes:
      - ./app:/app
      - ./conn/gcp.json:/gcp.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp.json
    ports:
      - "8080:80"
